# Generated by Django 5.0.6 on 2024-07-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nid',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
