# Generated by Django 5.0.6 on 2024-07-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_nid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='license_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
