# Generated by Django 5.0.6 on 2024-07-08 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_license_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='license_number',
        ),
    ]
