# Generated by Django 5.0.6 on 2024-07-28 17:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_delete_vaccineschedule'),
        ('patient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dose',
            unique_together={('user', 'vaccine', 'dose_number')},
        ),
        migrations.RemoveField(
            model_name='dose',
            name='administered_date',
        ),
    ]
