# Generated by Django 5.0.6 on 2024-07-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='doctor/images/')),
                ('name', models.CharField(max_length=50)),
                ('specialist', models.CharField(max_length=50)),
            ],
        ),
    ]
